### ISSUE TITLE
Known Issues & TO-DO

### ISSUE THREAD

**Issue by xiprox** [youkai-app/Youkai#22]
#### General
- [x] Fancy loading for text ([like this](https://i.imgur.com/gRVPHfG.png)). I'm thinking of writing a custom TextView to which you give some sample text like `app:textTemplate="The Legend of Dwakof"` and it, in practice, displays a light grey line with the same length. A better method would be to directly use `tools:text` but I don't think that's possible. [**DONE**](https://github.com/youkai-app/PlaceholderTextView)
- [ ] Rounded corner ripples/selectors for stuff like chevron buttons

#### Media Page
- [x] Air/publish status language
- [ ] Synopsis empty state strings (let's make these fun)
- [ ] Get reviews and characters via secondary requests to be able to limit counts and sort
- [ ] Favorite button (requires an API call with filtering and all)
- [ ] Expand the synopsis area with an animation instead of showing a dialog, maybe?
- [ ] Fix poster edge suddenly disappearing under the toolbar when scrolling
- [ ] Fix alternative titles not bold (geh)
- [x] Fix BarInfoView link colors (geh)
- [ ] YouTube icon too narrow
- [x] Most Popular and Highest Rated icons are centered instead of left aligned
- [ ] Last review item has extra bottom padding
- [ ] Fix `null` text for synonyms in Alternative Titles
- [ ] Don't use `original` for posters and covers

**Comment by dulleh** [comment]
- [ ] my fat fingers can't hit the login page links

**Comment by xiprox** [comment]
Moved over to [Asana](https://app.asana.com/0/422708842055106/422708842055106).
